<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RU1207211827" name="com.example.tests.ContactModificationTests" tests="3" failures="0" timestamp="10 Jul 2015 12:19:13 GMT" time="28.293" errors="2">
  <testcase name="modifySomeContact" time="9.481" classname="com.example.tests.ContactModificationTests">
    <error type="java.lang.AssertionError" message="Lists differ at element [18]: ContacnData [fname=dksgf, lname=gjkxsgkj, hnumber=123, mail1=email1@mail.ru] != ContacnData [fname=Regina, lname=gizatullina, hnumber=123, mail1=email1@mail.ru] expected [ContacnData [fname=dksgf, lname=gjkxsgkj, hnumber=123, mail1=email1@mail.ru]] but found [ContacnData [fname=Regina, lname=gizatullina, hnumber=123, mail1=email1@mail.ru]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [18]: ContacnData [fname=dksgf, lname=gjkxsgkj, hnumber=123, mail1=email1@mail.ru] != ContacnData [fname=Regina, lname=gizatullina, hnumber=123, mail1=email1@mail.ru] expected [ContacnData [fname=dksgf, lname=gjkxsgkj, hnumber=123, mail1=email1@mail.ru]] but found [ContacnData [fname=Regina, lname=gizatullina, hnumber=123, mail1=email1@mail.ru]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- modifySomeContact -->
  <testcase name="modifySomeContact" time="9.566" classname="com.example.tests.ContactModificationTests"/>
  <testcase name="modifySomeContact" time="9.246" classname="com.example.tests.ContactModificationTests">
    <error type="java.lang.AssertionError" message="Lists differ at element [28]: ContacnData [fname=test-36718992, lname=test-1095665827, hnumber=123, mail1=email1@mail.ru] != ContacnData [fname=test-448424689, lname=test-1080799449, hnumber=123, mail1=email1@mail.ru] expected [ContacnData [fname=test-36718992, lname=test-1095665827, hnumber=123, mail1=email1@mail.ru]] but found [ContacnData [fname=test-448424689, lname=test-1080799449, hnumber=123, mail1=email1@mail.ru]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [28]: ContacnData [fname=test-36718992, lname=test-1095665827, hnumber=123, mail1=email1@mail.ru] != ContacnData [fname=test-448424689, lname=test-1080799449, hnumber=123, mail1=email1@mail.ru] expected [ContacnData [fname=test-36718992, lname=test-1095665827, hnumber=123, mail1=email1@mail.ru]] but found [ContacnData [fname=test-448424689, lname=test-1080799449, hnumber=123, mail1=email1@mail.ru]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- modifySomeContact -->
</testsuite> <!-- com.example.tests.ContactModificationTests -->
